INSERT INTO `cine`.`pelicula` (`titulo`, `duracion`, `genero`, `clasificacion`) VALUES
('Inception', 148, 'Ciencia Ficción', 'PG-13'),
('The Dark Knight', 152, 'Acción', 'PG-13'),
('Interstellar', 169, 'Ciencia Ficción', 'PG-13'),
('Titanic', 195, 'Romance', 'PG-13'),
('The Matrix', 136, 'Ciencia Ficción', 'R'),
('Gladiator', 155, 'Acción', 'R'),
('Avatar', 162, 'Ciencia Ficción', 'PG-13'),
('The Godfather', 175, 'Drama', 'R'),
('Pulp Fiction', 154, 'Crimen', 'R'),
('Forrest Gump', 142, 'Drama', 'PG-13'),
('The Lion King', 88, 'Animación', 'G'),
('Star Wars: A New Hope', 121, 'Ciencia Ficción', 'PG'),
('Jurassic Park', 127, 'Aventura', 'PG-13'),
('The Avengers', 143, 'Acción', 'PG-13'),
('Fight Club', 139, 'Drama', 'R'),
('Toy Story', 81, 'Animación', 'G'),
('Schindler\'s List', 195, 'Drama', 'R'),
('The Lord of the Rings: The Fellowship of the Ring', 178, 'Fantasía', 'PG-13'),
('Spider-Man: Into the Spider-Verse', 117, 'Animación', 'PG'),
('Black Panther', 134, 'Acción', 'PG-13');
